Repository rai-09/sevaarth, pull requests merged in 2024-09, with the labels that each got.

#1 setup basic project structure
  .env.dev
  .env.prod
  .env.staging
  .eslintrc.json
  .gitignore
  README.md
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/images/logoSevaarth.png
  src/components/layout/Layout.js
  src/components/ui/Footer.js
  src/components/ui/NavBar.js
  src/pages/_app.js
  src/pages/about.js
  src/pages/donate.js
  src/pages/index.js
  src/pages/join.js
  src/styles/globals.css
  tailwind.config.js
Labels: enhancement, deployment

#2 setup CI/CD and manual trigger and resolve lint error
  .eslintrc.json
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/manual-preview-deploy.yml
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/layout/Layout.js
  src/components/ui/Footer.js
  src/pages/_app.js
  src/pages/about.js
  src/pages/donate.js
  src/pages/index.js
  src/pages/join.js
  tailwind.config.js
Labels: enhancement

#3 resolve error
  .vscode/settings.json
  src/components/layout/Layout.js
  src/pages/_app.js
  src/pages/_document.js
Labels: bug

#4 fix link issue
  .eslintrc.json
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/layout/Footer.js
  src/components/layout/Layout.js
  src/components/layout/NavBar.js
  src/components/ui/Hero.js
  src/components/ui/OurWork.js
  src/pages/404.js
  src/pages/500.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/_error.js
  src/pages/index.js
Labels: bug

#5 move dev changes to stg
  .env.dev
  .env.prod
  .env.staging
  .eslintrc.json
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/manual-preview-deploy.yml
  .gitignore
  .vscode/settings.json
  README.md
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/images/logoSevaarth.png
  src/components/layout/Footer.js
  src/components/layout/Layout.js
  src/components/layout/NavBar.js
  src/components/ui/Hero.js
  src/components/ui/OurWork.js
  src/pages/404.js
  src/pages/500.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/_error.js
  src/pages/about.js
  src/pages/donate.js
  src/pages/index.js
  src/pages/join.js
  src/styles/globals.css
  tailwind.config.js
Labels: deployment

#6 fix cd
  .github/workflows/continuous-deployment.yml
Labels: bug

#7 update CD
  .github/workflows/continuous-deployment.yml
Labels: bug

#8 update ci cd
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
Labels: bug

#9 lsit directory
  .github/workflows/continuous-integration.yml
Labels: bug

#10 check .next folder
  .github/workflows/continuous-integration.yml
Labels: bug

#11 fix cd
  .github/workflows/continuous-deployment.yml
Labels: bug

#12 add new workflow and updation ci and cd
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/manual-branch-update.yml
Labels: enhancement

#13 move dev changes to stg
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/manual-branch-update.yml
Labels: deployment

#14 move stg to main
  .env.dev
  .env.prod
  .env.staging
  .eslintrc.json
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/manual-branch-update.yml
  .github/workflows/manual-preview-deploy.yml
  .gitignore
  .vscode/settings.json
  README.md
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/images/logoSevaarth.png
  src/components/layout/Footer.js
  src/components/layout/Layout.js
  src/components/layout/NavBar.js
  src/components/ui/Hero.js
  src/components/ui/OurWork.js
  src/pages/404.js
  src/pages/500.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/_error.js
  src/pages/about.js
  src/pages/donate.js
  src/pages/index.js
  src/pages/join.js
  src/styles/globals.css
  tailwind.config.js
Labels: deployment

#15 list .next dir in cd
  .github/workflows/continuous-deployment.yml
Labels: bug

#16 move dev to stg
  .github/workflows/continuous-deployment.yml
Labels: deployment

#17 update cd
  .github/workflows/continuous-deployment.yml
Labels: bug

#18 Dev
  .github/workflows/continuous-deployment.yml
Labels: deployment

#20 bug fix
  .github/workflows/continuous-deployment.yml
  .github/workflows/manual-branch-update.yml
Labels: bug

#21 Feature/add workflow
  .github/workflows/continuous-deployment.yml
Labels: bug

#23 Fix workflow
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/manual-branch-update.yml
Labels: bug

#24 Dev
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/manual-branch-update.yml
Labels: deployment

#25 Stg
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/manual-branch-update.yml
Labels: deployment

#26 update CD
  .github/workflows/continuous-deployment.yml
Labels: bug

#27 update ci cd pipline
  .github/workflows/ci-cd-pipline.yml
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
Labels: bug

#35 Bug/build issue
  src/components/ui/ProgrammesSection.js
  src/pages/ourLegacy.js
Labels: bug

#36 resolve import issue
  src/components/ui/ProgrammesSection.js
  src/pages/ourLegacy.js
Labels: bug

#37 fix deployment confirm issue
  .github/workflows/ci-cd-pipline.yml
Labels: bug

#38 Responsive website
  src/components/layout/Footer.js
  src/components/layout/NavBar.js
  src/pages/getInvolved.js
  src/pages/ourLegacy.js
  src/pages/signUp.js
Labels: enhancement

#39 Linting error fix
  src/components/layout/Footer.js
  src/pages/ourLegacy.js
Labels: bug

#41 Merge branch 'stg' into dev
  .github/workflows/ci-cd-pipline.yml
Labels: bug

#44 Intigrate Vercel Analytics and SpeedInsights and update manual workflows
  .github/workflows/ci-cd-pipline.yml
  .github/workflows/manual-branch-update.yml
  .github/workflows/manual-preview-deploy.yml
  package-lock.json
  package.json
  src/pages/_document.js
Labels: enhancement

#45 change workflow name
  .github/workflows/manual-branch-merge.yml
Labels: enhancement

#46 fix issue
  .github/workflows/ci-cd-pipline.yml
Labels: bug

#47 fix again
  .github/workflows/ci-cd-pipline.yml
Labels: bug

#48 Add configurations
  eslint.config.mjs
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement

#49 fix issue
  .github/workflows/ci-cd-pipline.yml
  jest.config.js
  src/tests/index.test.js
Labels: bug

#52 Dev
  .github/workflows/manual-branch-merge.yml
  src/tests/index.test.js
Labels: deployment

#55 merge dev to main
  .env.dev
  .env.prod
  .env.staging
  .eslintrc.json
  .github/workflows/ci-cd-pipline.yml
  .github/workflows/manual-branch-merge.yml
  .github/workflows/manual-preview-deploy.yml
  .gitignore
  .vscode/settings.json
  README.md
  eslint.config.mjs
  jest.config.js
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/images/DISASTER RESPONSE.webp
  public/images/EDUCATION.png
  public/images/EMPOWERING GRASSROOTS.jpeg
  public/images/HEALTHCARE.png
  public/images/Livelihood.png
  public/images/Sevaarth curve.png
  public/images/WOMEN EMPOWERMENT.png
  public/images/ashok chakra.png
  public/images/logoSevaarth.png
  src/components/layout/Footer.js
  src/components/layout/Layout.js
  src/components/layout/NavBar.js
  src/components/ui/Hero.js
  src/components/ui/OurWork.js
  src/components/ui/ProgrammesSection.js
  src/pages/404.js
  src/pages/500.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/_error.js
  src/pages/contactUs.js
  src/pages/getInvolved.js
  src/pages/index.js
  src/pages/ourIntiatives.js
  src/pages/ourLegacy.js
  src/pages/signUp.js
  src/styles/globals.css
  src/tests/index.test.js
  tailwind.config.js
Labels: deployment

#57 update Hero.js
  src/components/ui/Hero.js
Labels: enhancement

#60 fix env
  .env.production
  .env.staging
Labels: bug

#61 update ci cd pipline
  .github/workflows/ci-cd-pipline.yml
  vercel.json
Labels: deployment

#63 fix ci cd pipline
  .github/workflows/ci-cd-pipline.yml
  package-lock.json
  package.json
  vercel.json
Labels: bug

#64 fix
  .github/workflows/ci-cd-pipline.yml
  vercel.json
Labels: bug

#65 fix pipeline
  .github/workflows/ci-cd-pipline.yml
  vercel.json
Labels: bug

#66 fix .
  .github/workflows/ci-cd-pipline.yml
Labels: bug

#67 fix deployment issue
  .github/workflows/ci-cd-pipline.yml
Labels: bug

#70 Bug/our work
  next.config.mjs
  public/images/Another child image.jpg
  public/images/Child image.jpg
  src/components/ui/Hero.js
  src/components/ui/OurWork.js
Labels: bug

#71 add img validation
  eslint.config.mjs
Labels: enhancement

#72 fix pr create issue on workflow run
  .github/workflows/manual-branch-merge.yml
Labels: enhancement

#73 fix syntax error
  .github/workflows/manual-preview-deploy.yml
Labels: bug

#74 Dev
  .github/workflows/manual-branch-merge.yml
  .github/workflows/manual-preview-deploy.yml
  eslint.config.mjs
  next.config.mjs
  public/images/Another child image.jpg
  public/images/Child image.jpg
  src/components/ui/Hero.js
  src/components/ui/OurWork.js
Labels: deployment

#76 Create Apis and update UI
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  src/components/layout/NavBar.js
  src/components/ui/Hero.js
  src/components/ui/donate.js
  src/components/ui/signUp.js
  src/lib/config.js
  src/lib/db.js
  src/lib/emailService.js
  src/models/Contact.js
  src/models/Donation.js
  src/models/Volunteer.js
  src/pages/api/contact.js
  src/pages/api/donation.js
  src/pages/api/paymentVerification.js
  src/pages/api/totalDonations.js
  src/pages/api/volunteer.js
  src/pages/api/volunteers.js
  src/pages/contactUs.js
  src/pages/getInvolved.js
Labels: enhancement

#77 Merging dev to stg
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  src/components/layout/NavBar.js
  src/components/ui/Hero.js
  src/components/ui/donate.js
  src/components/ui/signUp.js
  src/lib/config.js
  src/lib/db.js
  src/lib/emailService.js
  src/models/Contact.js
  src/models/Donation.js
  src/models/Volunteer.js
  src/pages/api/contact.js
  src/pages/api/donation.js
  src/pages/api/paymentVerification.js
  src/pages/api/totalDonations.js
  src/pages/api/volunteer.js
  src/pages/api/volunteers.js
  src/pages/contactUs.js
  src/pages/getInvolved.js
Labels: deployment

#78 Feat/info card comp
  src/components/ui/infoCards.js
  src/pages/getInvolved.js
  src/pages/index.js
  src/pages/ourLegacy.js
  src/styles/globals.css
  src/tests/index.test.js
  tailwind.config.js
Labels: enhancement

#79 update index.test.js
  src/tests/index.test.js
Labels: bug

#81 Update test
  src/components/ui/Donate.js
  src/components/ui/InfoCards.js
  src/components/ui/SignUp.js
Labels: bug
