Repository rai-09/sevaarth, pull requests merged in 2024-10, with the labels that each got.

#82 Feat/templte comp
  package-lock.json
  package.json
  public/images/20211107_161110.jpg
  public/images/20230108_123722.jpg
  public/images/FOOD.jpg
  public/images/GAREEB.jpg
  public/images/image.png
  src/components/common/alert.js
  src/components/common/button.js
  src/components/common/card.js
  src/components/common/input.js
  src/components/common/textarea.js
  src/components/layout/NavBar.js
  src/components/ui/Hero.js
  src/components/ui/InfoCards.js
  src/components/ui/Template.js
  src/pages/contactUs.js
  src/pages/index.js
  src/pages/ourIntiatives.js
  src/tests/index.test.js
Labels: enhancement

#84 Update/ourInitiatives
  src/components/common/badge.js
  src/components/common/card.js
  src/components/layout/NavBar.js
  src/components/ui/InfoCards.js
  src/pages/getInvolved.js
  src/pages/ourInitiatives.js
  src/pages/ourIntiatives.js
Labels: enhancement

#85 Update ourLegacy.js
  src/components/ui/temp.js
  src/pages/getInvolved.js
  src/pages/ourLegacy.js
Labels: enhancement

#87 Update/our legacy.js
  src/components/common/checkbox.js
  src/components/common/dialog.js
  src/components/common/label.js
  src/components/common/select.js
  src/components/ui/Donate.js
  src/components/ui/SignUp.js
  src/components/ui/legacy.js
  src/components/ui/temp.js
  src/models/Volunteer.js
  src/pages/api/volunteer.js
  src/pages/contactUs.js
  src/pages/getInvolved.js
  src/pages/index.js
  src/tests/index.test.js
Labels: enhancement

#88 fix issue
  .env.
  .env.staging
  src/components/common/Alert.js
  src/components/common/Badge.js
  src/components/common/Button.js
  src/components/common/Card.js
  src/components/common/Checkbox.js
  src/components/common/Dialog.js
  src/components/common/Input.js
  src/components/common/Label.js
  src/components/common/Select.js
  src/components/common/Textarea.js
  src/components/ui/Legacy.js
  src/components/ui/SignUp.js
  src/components/ui/Temp.js
Labels: bug

#90 Fix Navbar active link issue
  package-lock.json
  package.json
  src/components/layout/NavBar.js
  src/pages/api/totalDonations.js
  src/pages/donate.js
  src/styles/globals.css
  tailwind.config.js
Labels: bug

#91 Feature/update configs
  .env.development
  README.md
  eslint.config.mjs
  jest.config.js
  next.config.mjs
  package-lock.json
  package.json
  public/images/childrens.jpg
  public/images/school students.jpg
Labels: enhancement

#92 Move dev changes to stg
  .env.production
  .env.staging
  README.md
  eslint.config.mjs
  jest.config.js
  next.config.mjs
  package-lock.json
  package.json
  public/favicon.ico
  public/images/20211107_161110.jpg
  public/images/20230108_123722.jpg
  public/images/FOOD.jpg
  public/images/GAREEB.jpg
  public/images/childrens.jpg
  public/images/image.png
  public/images/school students.jpg
  src/components/common/Alert.js
  src/components/common/Badge.js
  src/components/common/Button.js
  src/components/common/Card.js
  src/components/common/Checkbox.js
  src/components/common/Dialog.js
  src/components/common/Input.js
  src/components/common/Label.js
  src/components/common/Select.js
  src/components/common/Textarea.js
  src/components/layout/Footer.js
  src/components/layout/NavBar.js
  src/components/ui/Donate.js
  src/components/ui/Hero.js
  src/components/ui/InfoCards.js
  src/components/ui/Legacy.js
  src/components/ui/SignUp.js
  src/components/ui/Temp.js
  src/components/ui/TermsModal.js
  src/components/ui/donate.js
  src/components/ui/signUp.js
  src/lib/db.js
  src/models/Volunteer.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/api/totalDonations.js
  src/pages/api/volunteer.js
  src/pages/contactUs.js
  src/pages/donate.js
  src/pages/getInvolved.js
  src/pages/index.js
  src/pages/ourInitiatives.js
  src/pages/ourIntiatives.js
  src/pages/ourLegacy.js
  src/styles/globals.css
  src/tests/index.test.js
  tailwind.config.js
Labels: deployment

#93 Add new pages and Update OurInitiative page
  README.md
  next.config.mjs
  package-lock.json
  package.json
  src/components/layout/Footer.js
  src/components/ui/Temp.js
  src/models/Initiative.js
  src/pages/404.js
  src/pages/500.js
  src/pages/api/initiatives.js
  src/pages/donate.js
  src/pages/getInvolved.js
  src/pages/ourInitiatives.js
  src/pages/resources/faq.js
  src/pages/resources/privacy-policy.js
Labels: enhancement

#94 Dev
  README.md
  next.config.mjs
  package-lock.json
  package.json
  src/components/layout/Footer.js
  src/components/ui/Temp.js
  src/models/Initiative.js
  src/pages/404.js
  src/pages/500.js
  src/pages/api/initiatives.js
  src/pages/donate.js
  src/pages/getInvolved.js
  src/pages/ourInitiatives.js
  src/pages/resources/faq.js
  src/pages/resources/privacy-policy.js
Labels: deployment

#97 Update CI CD Pipelines
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/cd-stg.yml
  .github/workflows/ci.yml
  .github/workflows/manual-branch-merge.yml
  .github/workflows/manual-preview-deploy.yml
Labels: enhancement

#98 Update dev cd
  .github/workflows/cd-dev.yml
Labels: bug

#99 Dev to stg
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/cd-stg.yml
  .github/workflows/ci.yml
  .github/workflows/manual-branch-merge.yml
  .github/workflows/manual-preview-deploy.yml
  next.config.mjs
  package-lock.json
  package.json
  src/components/layout/Footer.js
  src/components/layout/NavBar.js
  src/components/ui/Partner.js
  src/components/ui/Temp.js
  src/models/Partner.js
  src/pages/api/partners.js
  src/pages/index.js
  src/tests/index.test.js
Labels: deployment

#100 Stg
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/cd-stg.yml
  .github/workflows/ci.yml
  .github/workflows/manual-branch-merge.yml
  .github/workflows/manual-preview-deploy.yml
  next.config.mjs
  package-lock.json
  package.json
  src/components/layout/Footer.js
  src/components/layout/NavBar.js
  src/components/ui/Partner.js
  src/components/ui/Temp.js
  src/models/Partner.js
  src/pages/api/partners.js
  src/pages/index.js
  src/tests/index.test.js
Labels: deployment

#101 Add Licenses and update Readme
  LICENSE
  LICENSE-CC
  README.md
Labels: documentation, enhancement
